name = "LAModels"
uuid = "549c886d-99d8-421c-88dc-0905baac72aa"
authors = ["Vivak Patel <vp314@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
